### PR TITLE
Update

### LINKED ISSUE #6: comments broken?
block comments seem ok,

image

### LINKED ISSUE #7: Add Bracket Pair Highlighting

### LINKED ISSUE #9: numbers inside names, bug?
image

image

### PR DESCRIPTION
**Pull request by FreHu**
Resolves #7 , 
Resolves #6 ,
Resolves #9

### CODE REVIEW

**Comment by FreHu** [comment]
new version published

**Comment by larshp** [comment]
better

comments have the same color as annotations

and identifieres with numbers have a different color than identifiers without numbers,

image

**Comment by FreHu** [comment]
i'm not sure what category the annotations best fit into, but they are labeled as `comment.line.annotation.property.lvlX.abapcds` so you can customize them (see readme)

**Comment by FreHu** [comment]
what i can do is contribute some defaults for the annotation colors https://code.visualstudio.com/api/references/contribution-points#contributes.configurationDefaults

**Pull request merged**
